Repository IATI/IATI-Rulesets, pull requests merged in 2018-02, with the labels that each got.

#67 Revert "Check that there is a non-empty narrative when there is no ref"
  rulesets/standard.json
Labels: bug, complete

#59 Fix result value rules
  iatirulesets/__init__.py
  meta_tests.sh
  meta_tests/result_indicator_baseline_selector_with_conditions.json
  meta_tests/result_indicator_period_actual_selector_with_conditions.json
  meta_tests/result_indicator_period_target_selector_with_conditions.json
  meta_tests/results_indicator_baseline_value_bad.xml
  meta_tests/results_indicator_baseline_value_good.xml
  meta_tests/results_indicator_baseline_value_not_relevant.xml
  meta_tests/results_indicator_period_actual_value_bad.xml
  meta_tests/results_indicator_period_actual_value_good.xml
  meta_tests/results_indicator_period_actual_value_not_relevant.xml
  meta_tests/results_indicator_period_target_value_bad.xml
  meta_tests/results_indicator_period_target_value_good.xml
  meta_tests/results_indicator_period_target_value_not_relevant.xml
  rulesets/standard.json
Labels: activity standard, complete, enhancement

#62 Add a test for the results references rule
  meta_tests.sh
  meta_tests/results_references.json
  meta_tests/results_refs_bad.xml
  meta_tests/results_refs_good.xml
Labels: activity standard, enhancement, incomplete

#70 Add text output for no_more_than_one Rule
  iatirulesets/text.py
Labels: complete, enhancement

#71 Update text.py - 'no_more_than_one' output
  iatirulesets/text.py
Labels: complete, enhancement

#57 Merge 2.03 development to 2.03 live branch
  iatirulesets/__init__.py
  iatirulesets/text.py
  meta_tests.sh
  meta_tests/result_indicator_baseline_selector_with_conditions.json
  meta_tests/result_indicator_period_actual_selector_with_conditions.json
  meta_tests/result_indicator_period_target_selector_with_conditions.json
  meta_tests/results_indicator_baseline_value_bad.xml
  meta_tests/results_indicator_baseline_value_good.xml
  meta_tests/results_indicator_baseline_value_not_relevant.xml
  meta_tests/results_indicator_period_actual_value_bad.xml
  meta_tests/results_indicator_period_actual_value_good.xml
  meta_tests/results_indicator_period_actual_value_not_relevant.xml
  meta_tests/results_indicator_period_target_value_bad.xml
  meta_tests/results_indicator_period_target_value_good.xml
  meta_tests/results_indicator_period_target_value_not_relevant.xml
  meta_tests/results_references.json
  meta_tests/results_refs_bad.xml
  meta_tests/results_refs_good.xml
  rulesets/standard.json
Labels: complete, enhancement
