Repository IATI/IATI-Rulesets, pull requests merged in 2019-03, with the labels that each got.

#160 Ensure rule is applied for _all_ activity budgets (v2.03)
  rulesets/standard.json
Labels: 2.03

#159 Checks to ensure status and dates correspond (v2.03)
  meta_tests.sh
  meta_tests/status_date.json
  meta_tests/status_date_bad.xml
  meta_tests/status_date_good.xml
  rulesets/standard.json
  schema.json
Labels: 2.03

#164 (2.01) provider-org and receiver-org checked under atleast_one
  rulesets/standard.json
Labels: 2.01

#165 (2.02) provider_org and receiver_org checked under atleast_one
  rulesets/standard.json
Labels: 2.02

#166 (2.03) provider_org and receiver_org checked under atleast_one #162
  rulesets/standard.json
Labels: 2.03

#169 (2.03) Attempt to fix how and where rules are rendered in page #163
  iatirulesets/text.py
Labels: 2.03

#168 (2.02) Attempt to fix how and where rules are rendered in page #163
  iatirulesets/text.py
Labels: 2.02

#167 (2.01) Attempt to fix how and where rules are rendered in page #163
  iatirulesets/text.py
Labels: 2.01

#172 (2.03) Render 'condition' when present in atleast_one rule
  iatirulesets/text.py
Labels: 2.03

#171 (2.02) Render 'condition' when present in atleast_one rule
  iatirulesets/text.py
Labels: 2.02

#170 (2.01) Render 'condition' when present in atleast_one rule
  iatirulesets/text.py
Labels: 2.01

#175 (2.01) Added range rule
  iatirulesets/__init__.py
  iatirulesets/text.py
  meta_tests.sh
  meta_tests/range.json
  meta_tests/range_bad.xml
  meta_tests/range_good.xml
  rulesets/standard.json
  rulestable.py
  schema.json
Labels: 2.01

#176 (2.02) Added range rule
  iatirulesets/__init__.py
  iatirulesets/text.py
  meta_tests.sh
  meta_tests/range.json
  meta_tests/range_bad.xml
  meta_tests/range_good.xml
  rulesets/standard.json
  rulestable.py
  schema.json
Labels: 2.02

#174 (2.03) Adding new range rule
  iatirulesets/__init__.py
  iatirulesets/text.py
  meta_tests.sh
  meta_tests/range.json
  meta_tests/range_bad.xml
  meta_tests/range_good.xml
  rulesets/standard.json
  rulestable.py
  schema.json
Labels: 2.03
