Repository IATI/IATI-Rulesets, pull requests merged in 2019-02, with the labels that each got.

#103 Remove PHP references and code (version 2.01)
  .travis.yml
  README.rst
  testrules.php
Labels: 2.01

#104 Remove PHP references and code (2.02)
  .travis.yml
  README.rst
  testrules.php
Labels: 2.02

#105 Remove PHP references and code (2.03)
  .travis.yml
  README.rst
  testrules.php
Labels: 2.03

#106 Remove schemadoc.py and meta_tests.py (2.01)
  meta_tests.py
  schemadoc.py
Labels: 2.01

#107 Remove schemadoc.py and meta_tests.py (2.02)
  meta_tests.py
  schemadoc.py
Labels: 2.02

#108 Remove schemadoc.py and meta_tests.py (2.03)
  meta_tests.py
  schemadoc.py
Labels: 2.03

#98 [2.01] Adding one_or_all rule and at_least_one update
  SPEC.rst
  iatirulesets/__init__.py
  meta_tests.sh
  meta_tests/at_least_one.json
  meta_tests/at_least_one_bad.xml
  meta_tests/at_least_one_narrative.xml
  meta_tests/at_least_one_ref.xml
  meta_tests/one_or_all.json
  meta_tests/one_or_all_currency_all_bad.xml
  meta_tests/one_or_all_currency_all_good.xml
  meta_tests/one_or_all_currency_bad.xml
  meta_tests/one_or_all_currency_good.xml
  meta_tests/one_or_all_lang_bad.xml
  meta_tests/one_or_all_lang_bad_all.xml
  meta_tests/one_or_all_lang_good.xml
  meta_tests/one_or_all_lang_good_all.xml
  meta_tests/one_or_all_sector_all_bad.xml
  meta_tests/one_or_all_sector_all_good.xml
  meta_tests/one_or_all_sector_bad.xml
  meta_tests/one_or_all_sector_good.xml
  meta_tests/recipient_country.json
  meta_tests/recipient_country_bad.xml
  meta_tests/recipient_country_good.xml
  rulesets/standard.json
  rulestable.py
Labels: 2.01

#99 New rule: if_this_then_that
  SPEC.rst
  iatirulesets/__init__.py
  iatirulesets/text.py
  meta_tests.sh
  meta_tests/if_then.json
  meta_tests/if_then_bad.xml
  meta_tests/if_then_good.xml
  rulesets/standard.json
  rulestable.py
Labels: 2.01

#122 [2.01] Add rule: between_dates
  SPEC.rst
  iatirulesets/__init__.py
  meta_tests.sh
  meta_tests/between_dates.json
  meta_tests/between_dates_bad.xml
  meta_tests/between_dates_good.xml
  rulestable.py
Labels: 2.01

#120 [2.01] Adding time limit for org-files
  iatirulesets/__init__.py
  meta_tests.sh
  meta_tests/time_limit.json
  meta_tests/time_limit_bad.xml
  meta_tests/time_limit_good.xml
  rulesets/standard.json
Labels: 2.01

#123 Run jsonlint on standard.json
  .travis.yml
  rulesets/standard.json
Labels: enhancement

#95 [2.01] Add only_one_of rule
  SPEC.rst
  iatirulesets/__init__.py
  iatirulesets/text.py
  meta_tests.sh
  meta_tests/only_one_of.json
  meta_tests/only_one_of_activity_bad.xml
  meta_tests/only_one_of_activity_good.xml
  meta_tests/only_one_of_transaction_bad.xml
  meta_tests/only_one_of_transaction_good.xml
  rulesets/standard.json
  rulestable.py
Labels: 2.01

#118 [201] one_or_all rules for org-files
  meta_tests.sh
  meta_tests/one_or_all_org.json
  meta_tests/one_or_all_org_currency_bad.xml
  meta_tests/one_or_all_org_currency_good.xml
  rulesets/standard.json
Labels: 2.01

#124 [2.01] Updating descriptive files to include new rules.
  README.rst
  SPEC.rst
  rulesets/standard.json
  rulestable.py
  schema.json
Labels: 2.01

#130 [2.01] Fix time_limit rule, adding dateutils
  iatirulesets/__init__.py
  meta_tests/time_limit_bad.xml
  meta_tests/time_limit_good.xml
  requirements.txt
  rulesets/standard.json
Labels: 2.01

#131 [2.01] Updating text.py to include all the new rules
  iatirulesets/text.py
Labels: 2.01

#132 Fix 2 descriptions that were not rendering correctly
  iatirulesets/text.py
Labels: 2.01

#133 [2.01] Rearrange standard.json and fine-tune time_limit
  iatirulesets/__init__.py
  meta_tests/between_dates.json
  meta_tests/between_dates_bad.xml
  meta_tests/period_time_bad.xml
  meta_tests/time_limit.json
  rulesets/standard.json
Labels: 2.01

#134 Checking that if @ref doesn't exist, narrative exists (for provider-o…
  rulesets/standard.json
Labels: 2.02

#135 [2.02] Policy-marker rules
  iatirulesets/__init__.py
  rulesets/standard.json
Labels: 2.02

#136 Add policy-marker/@significance rule and fix tree.findall()
  iatirulesets/__init__.py
  rulesets/standard.json
Labels: 2.01

#138 Fixed indentation in travis.yml
  .travis.yml
  rulesets/standard.json
Labels: 2.02

#139 Added time_limit rules for receipient-budget-region and total-expenditure
  meta_tests.sh
  meta_tests/recipient_region_budget.json
  meta_tests/recipient_region_budget_bad.xml
  meta_tests/recipient_region_budget_good.xml
  meta_tests/total_expenditure.json
  meta_tests/total_expenditure_bad.xml
  meta_tests/total_expenditure_good.xml
  rulesets/standard.json
Labels: 2.02

#141 Reverting loop and strict_sum rules
  iatirulesets/__init__.py
  meta_tests.sh
  meta_tests/forloop.json
  meta_tests/forloop_bad.xml
  meta_tests/forloop_good.xml
  meta_tests/sector_percentage_sum.json
  meta_tests/sector_percentage_sum_bad.xml
  meta_tests/sector_percentage_sum_good.xml
  rulesets/standard.json
Labels: 2.03

#144 [2.01] Fix ruleset rendering after adding new rules
  iatirulesets/text.py
Labels: 2.01

#145 [2.02] Fix ruleset rendering after adding new ones
  iatirulesets/text.py
Labels: 2.02

#150 Ensure percentages are a number between 0 and 100
  meta_tests/evaluates_to_true.json
  meta_tests/evaluates_to_true_bad.xml
  rulesets/standard.json
Labels: 2.03

#152 Added new quantitative @value rule check
  meta_tests/if_then.json
  meta_tests/if_then_bad.xml
  rulesets/standard.json
Labels: 2.03
